version: "3.2"
services:
  jwt-queries:
    volumes:
      - ./jwt/:/mnt/
    build: ./jwt
    working_dir: /backend/
    command: sh run.sh

  routes-queries:
    volumes:
      - ./rutas/:/mnt/
    build: ./rutas
    working_dir: /backend/
    command: sh run_queries.sh
    depends_on:
      - jwt-queries

  products-queries:
    volumes:
      - ./bodegas/:/mnt/
    build:
      context: ./bodegas
      dockerfile: api.Dockerfile
    working_dir: /backend/
    command: sh api.sh
    depends_on:
      - jwt-queries

  nginx:
    image: nginx:latest
    ports:
      - 8000:443
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx/localhost.key:/etc/ssl/private/localhost.key
    depends_on:
      - jwt-queries
      - routes-queries
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  redis:
    image: redis
    volumes: 
      - ./data:/data

  products-healthy-events:
    volumes:
      - ./bodegas/:/mnt/
    build:
      context: ./bodegas
      dockerfile: events.Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    working_dir: /backend/
    environment:
      - WORKER_TYPE=HEALTHY
    env_file:
      - events.env
    command: sh events.sh
    depends_on:
      - rabbitmq

  products-flaky-events:
    volumes:
      - ./bodegas/:/mnt/
    build:
      context: ./bodegas
      dockerfile: events.Dockerfile
    deploy:
      mode: replicated
      replicas: 1
    working_dir: /backend/
    environment:
      - WORKER_TYPE=FLAKY
      - FAILURE_PROBABILITY=75
    env_file:
      - events.env
    command: sh events.sh
    depends_on:
      - rabbitmq

  voting-responses:
    volumes:
      - ./votaciones/:/mnt/
    build:
      context: ./votaciones
      dockerfile: events.Dockerfile
    working_dir: /backend/
    env_file:
      - events.env
    command: sh run_responses.sh
    depends_on:
      - rabbitmq

  voting-requests:
    volumes:
      - ./votaciones/:/mnt/
    build:
      context: ./votaciones
      dockerfile: events.Dockerfile
    working_dir: /backend/
    environment:
      - NUM_REQUESTS=5
    env_file:
      - events.env
    command: sh run_requests.sh
    depends_on:
      - rabbitmq
      - products-healthy-events
      - products-flaky-events
      - voting-responses
