version: "3.2"
services:
  jwt-queries:
    volumes:
      - ./jwt/:/mnt/
    build: ./jwt
    working_dir: /backend/
    command: sh run.sh

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  routes-queries:
    volumes:
      - ./rutas/:/mnt/
    build: ./rutas
    working_dir: /backend/
    command: sh run_queries.sh
    depends_on:
      - jwt-queries

  products-queries:
    volumes:
      - ./bodegas/:/mnt/
    build:
      context: ./bodegas
      dockerfile: api.Dockerfile
    working_dir: /backend/
    command: sh api.sh
    depends_on:
      - jwt-queries

  products-events:
    volumes:
      - ./bodegas/:/mnt/
    build:
      context: ./bodegas
      dockerfile: events.Dockerfile
    working_dir: /backend/
    environment:
      - PYTHONUNBUFFERED=1
    command: sh events.sh
    depends_on:
      - rabbitmq

  voting-events:
    volumes:
      - ./votaciones/:/mnt/
    build:
      context: ./votaciones
      dockerfile: events.Dockerfile
    working_dir: /backend/
    environment:
      - PYTHONUNBUFFERED=1
    command: sh events.sh
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:latest
    ports:
      - 8000:443
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx/localhost.key:/etc/ssl/private/localhost.key
    depends_on:
      - jwt-queries
      - routes-queries
  
  monitor-rutas:
    volumes:
      - ./monitor-rutas/:/mnt/
      - ./monitor-rutas/output:/backend/output
    build: ./monitor-rutas
    working_dir: /backend/
    command: sh run.sh
    env_file: 
      - ./monitor-rutas/.env
    depends_on:
      - routes-queries
