version: "3.2"
services:
  jwt-queries:
    volumes:
      - ./jwt/:/mnt/
    build: ./jwt
    working_dir: /backend/
    command: sh run.sh

  routes-queries:
    volumes:
      - ./rutas/:/mnt/
    build: ./rutas
    working_dir: /backend/
    command: sh run_queries.sh
    depends_on:
      - jwt-queries

  nginx:
    image: nginx:latest
    ports:
      - 8000:443
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx/localhost.key:/etc/ssl/private/localhost.key
    depends_on:
      - jwt-queries
      - routes-queries
